import Head from 'next/head'
import Image from 'next/image'
import { Map } from '../components/Map'
import { useData } from '../hooks/useData'
import styles from '../styles/Home.module.css'

function Footer() {
  return (
    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  )
}

export default function Home() {
  const { data, error } = useData()

  return (
    <div className={styles.container}>
      <Head>
        <title>Dataviz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Dataviz</h1>
        {error && (
          <div>Error! {error.message}</div>
        )}
        {data ? (
          <Map events={data.events} />
        ) : (
          <div>Loading...</div>
        )}
      </main>
      <Footer />
    </div>
  )
}
